### ISSUE TITLE
Add a check on filesystems

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-healthcheck#13]
Some filesystems (e.g. NFS ones) may have issues that would lead to
```
ls /xxx
ls: cannot access '/xxx Stale file handle
```
we should define the minimal check that would find this issue, and add it to the list of implemented ones. The call signature could be like
```yaml
  - name: "Check mounts"
    function_name: check_mounts
    kwargs:
      mounts: "/aaa", "/bbb"
```
and the basic version would be to simply call `ls` on each folder and look for errors.
